p8105_hw2_lka2128
================
Liam Albert
2026-10-08

# Problem 1

``` r
library(tidyverse)
library(janitor)

subway_df = read_csv(
  "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  clean_names() |>
  select(
    line, station_name, station_latitude,
    station_longitude, starts_with("route"),
    entry, vending, entrance_type, ada
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
)

nrow(subway_df)
```

    ## [1] 1868

``` r
ncol(subway_df)
```

    ## [1] 19

## Data Description

The NYC Transit dataset contains information about subway station
entrances and exits throughout New York City. Variables include subway
lines, station names, geographic coordinates, routes served, entry
permissions, vending availability, entrance types, and ADA compliance.

The cleaned datasets contain 1868 rows and 19 columns

## Distinct Stations

``` r
subway_df |> 
    distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct subway stations

## ADA Compliance

``` r
subway_df |>
  filter(ada == TRUE) |>
  nrow()
```

    ## [1] 468

There are 468 ADA-compliant stations

## Vending and Entrance

``` r
subway_df |>
  filter(vending == "NO") |>
  summarize(
    proportion = mean(entry, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1      0.377

The proportion of entrances and exits without vending that allows
entrance is 0.377.

# Problem 2

``` r
library(readxl)
library (tidyverse)
library (janitor)

mr_trash_df= read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N742"
) |>
  clean_names() |> 
  filter(!is.na(dumpster)) |>
  mutate(
    year= as.numeric(year),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

prof_trash_df = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M139"
) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.numeric(year),
    plastic_bottles = as.numeric(plastic_bottles),
    trash_wheel = "Professor Trash Wheel"
  )

gwynnda_df = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda the Good Wheel of the W",
  range = "A2:L394"
) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.numeric(year),
    trash_wheel = "Gwynnda"
  )

trash_df = bind_rows(
  mr_trash_df,
  prof_trash_df,
  gwynnda_df
)

nrow(trash_df)
```

    ## [1] 1269

``` r
trash_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         295.

``` r
trash_df |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarize(
    total_cigarettes = sum(cigarette_butts, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_cigarettes
    ##              <dbl>
    ## 1            18120

The Trash Wheel data set contains information about trash collected by
Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda. Variables included
are dumpster number, date, trash weight, and types of litter collected.
Data was cleaned by removing unnecessary rows, variable renamed,
converting data types, and combining the three data sets. There were
1,269 observations. Professor Trash Wheel collected 295 tons of trash
and Gwynnda collected 18,120 cigarette butts in June 2022.
